-- PROCEDURE PARA RETORNAR O SALARIO BRUTO
ALTER PROCEDURE SP_SALARIO_BRUTO
(@MATRICULA_FUNCIONARIO MONEY, @SAL_BRUTO MONEY OUTPUT)
AS
BEGIN
	IF @MATRICULA_FUNCIONARIO IN (SELECT MATRICULA FROM FUNCIONARIOS)
		BEGIN
			SELECT	@SAL_BRUTO = C.SALARIO
			FROM	FUNCIONARIOS F
				INNER JOIN CARGOS C ON C.CARGO = F.CARGO
			WHERE F.MATRICULA = @MATRICULA_FUNCIONARIO
		END
	ELSE
		BEGIN
			SET @SAL_BRUTO = -1
			PRINT 'SP_SALARIO_BRUTO: MATRÍCULA INVÁLIDA'
		END
END

