ALTER PROCEDURE SP_CALCULAR_INSS
(@MATRICULA_FUNCIONARIO VARCHAR(4), @DESCONTO_INSS MONEY OUTPUT)
AS
BEGIN
	IF @MATRICULA_FUNCIONARIO IN (SELECT MATRICULA FROM FUNCIONARIOS)
		BEGIN
			DECLARE	@ALIQUOTA DECIMAL(5,3),
					@DIFERENCA MONEY,
					@AGREGADO MONEY,
					@FAIXA INT,
					@SALARIO_BRUTO MONEY,
					@SALARIO_CONTRIBUICAO MONEY,
					@PROVENTOS MONEY

			-- DEFININDO O VALOR DO SALARIO BRUTO
			EXEC SP_SALARIO_BRUTO @MATRICULA_FUNCIONARIO, @SALARIO_BRUTO OUTPUT

			-- SOMANDO OS PROVENTOS
			EXEC SP_SOMAR_PROVENTOS @MATRICULA_FUNCIONARIO, @PROVENTOS OUTPUT

			-- DEFININDO O SALARIO DE CONTRIBUIÇÃO
			SET @SALARIO_CONTRIBUICAO = @SALARIO_BRUTO + @PROVENTOS

			-- VERIFICANDO SE O SALARIO É MAIOR QUE O TETO DO INSS, SE FOR RETORNAR O DESCONTO_INSS E ENCERRA A PROCEDURE
			IF @SALARIO_CONTRIBUICAO > (SELECT VMAX FROM CONTRIBUICAO_PREVIDENCIARIA_INSS WHERE FAIXA = 4)
				BEGIN
					SET @DESCONTO_INSS = (SELECT SUM((VMAX-VMIN) * (ALIQUOTA/100)) FROM CONTRIBUICAO_PREVIDENCIARIA_INSS)
				END
			-- SE NÃO FOR MAIOR, EXECUTA ISSO
			ELSE 
				BEGIN
					-- DEFININDO A FAIXA, ALIQUOTA E A DIFERENÇA REFERENTE AO SALARIO DE CONTRIBUICAO
					SELECT	@FAIXA = FAIXA,
							@ALIQUOTA = ALIQUOTA/100,
							@DIFERENCA = VMIN
					FROM CONTRIBUICAO_PREVIDENCIARIA_INSS
					WHERE @SALARIO_BRUTO BETWEEN VMIN AND VMAX


					-- ADICIONANDO VALOR A AGREGAR
					SET @AGREGADO = 0
					IF @FAIXA > 1 -- SE FOR DA FAIXA 1 NÃO PRECISA AGREGAR NADA
						BEGIN
							SET @AGREGADO = ((SELECT SUM((VMAX-VMIN) * (ALIQUOTA/100))
											 FROM CONTRIBUICAO_PREVIDENCIARIA_INSS
											 WHERE FAIXA < @FAIXA))
						END

					--DEFININDO A DIFERENÇA A SER TIRADA
					SET @DESCONTO_INSS = ((@SALARIO_CONTRIBUICAO - @DIFERENCA) * (@ALIQUOTA)) - @AGREGADO
				END
		END
END


--CHAMADA DA PROCEDURE
DECLARE	@INSS DECIMAL(5,2)
EXEC SP_CALCULAR_INSS 1060, @INSS OUTPUT 
SELECT @INSS AS DESCONTO_DO_INSS