-- CRIACAO DA PROCEDURE DO CALCULO DO REPOUSO REMUNERADO
CREATE PROCEDURE SP_REPOUSO_REMUNERADO
(@SALARIO_BRUTO MONEY, @BONUS_REPOUSO MONEY OUTPUT)
AS
BEGIN
	DECLARE @PORC DECIMAL(5,2)
	SET @PORC = (SELECT * FROM REPOUSO_REMUNERADO) / 100
	SET @BONUS_REPOUSO = @SALARIO_BRUTO * @PORC
END

-- TESTE
DECLARE @SAL_BRUTO MONEY, @REPOUSO_REMU MONEY
SELECT @SAL_BRUTO = C.SALARIO FROM FUNCIONARIOS F INNER JOIN CARGOS C ON C.CARGO = F.CARGO WHERE MATRICULA = 1002

EXEC SP_REPOUSO_REMUNERADO @SAL_BRUTO, @REPOUSO_REMU OUTPUT
SELECT	@SAL_BRUTO AS SALARIO,
		@REPOUSO_REMU AS REMUNERACAO