-- CRIACAO DA PROCEDURE DO CALCULO DO REPOUSO REMUNERADO
ALTER PROCEDURE SP_REPOUSO_REMUNERADO
(@MATRICULA_FUNCIONARIO VARCHAR(4), @BONUS_REPOUSO MONEY OUTPUT)
AS
BEGIN
	-- VARIAVEIS DA PROCEDURE
	DECLARE @PORC DECIMAL(5,2),
			@SALARIO_BRUTO MONEY
	
	--DEFININDO O SALARIO BRUTO
	EXEC SP_SALARIO_BRUTO @MATRICULA_FUNCIONARIO, @SALARIO_BRUTO OUTPUT

	-- DEFININDO O PERCENTUAL DE BONUS
	SET @PORC = (SELECT * FROM REPOUSO_REMUNERADO) / 100
	
	-- DEFININDO O VALOR DO SALARIO REPOUSO
	SET @BONUS_REPOUSO = @SALARIO_BRUTO * @PORC
END

-- TESTE
DECLARE @REPOUSO_REMU MONEY

EXEC SP_REPOUSO_REMUNERADO 1060, @REPOUSO_REMU OUTPUT
SELECT	@REPOUSO_REMU AS REMUNERACAO