CREATE PROCEDURE SP_DEDUCAO_POR_DEPENDENTE
(@MATRICULA_FUNCIONARIO VARCHAR(4), @DEDUCAO_TOTAL MONEY OUTPUT)
AS
BEGIN
	IF @MATRICULA_FUNCIONARIO IN (SELECT MATRICULA FROM FUNCIONARIOS)
		BEGIN
			-- VARIAVEL LOCAL
			DECLARE @QTD_DEPENDENTES INT,
					@DEDUCAO MONEY

			-- OBTENDO A QUANTIDADE DE DEPENDENTES
			SELECT @QTD_DEPENDENTES = DEPENDENTES
			FROM FUNCIONARIOS
			WHERE MATRICULA = @MATRICULA_FUNCIONARIO

			-- OBTENDO O VALOR DE DEDUÇÃO
			SELECT @DEDUCAO = DEDUCAO FROM DEPENDENTE

			--RETORNANDO O VALOR DE DEDUÇÃO POR DEPENDETES
			SET @DEDUCAO_TOTAL = @QTD_DEPENDENTES * @DEDUCAO
		END
	ELSE
		BEGIN
			SET @DEDUCAO = -1
			PRINT 'SP_DEDUCAO_POR_DEPENDENTE: MATRÍCULA INVÁLIDA'
		END
END

-- SELECT MATRICULA, DEPENDENTES FROM FUNCIONARIOS

-- TESTE
DECLARE @VALOR MONEY
EXEC SP_DEDUCAO_POR_DEPENDENTE 1060, @VALOR OUTPUT
SELECT @VALOR AS VALOR_A_SER_DEDUZIDO