ALTER PROCEDURE SP_CALCULAR_IRRF
(@MATRICULA_FUNCIONARIO VARCHAR(4), @VALOR_IRRF MONEY OUTPUT)
AS
BEGIN
	IF @MATRICULA_FUNCIONARIO IN (SELECT MATRICULA FROM FUNCIONARIOS)
		BEGIN
			-- VARIAVEIS
			DECLARE @ALIQUOTA MONEY,
					@PARC MONEY,
					@SALARIO_BRUTO MONEY,
					@INSS MONEY,
					@PROVENTOS MONEY,
					@DEPENDENTES MONEY,
					@BASE_CALCULO MONEY

			-- SETANDO OS VALORES DAS VARIAVEIS
			EXEC SP_SALARIO_BRUTO @MATRICULA_FUNCIONARIO, @SALARIO_BRUTO OUTPUT
			
			-- SETANDO O VALOR DO INSS
			EXEC SP_CALCULAR_INSS @MATRICULA_FUNCIONARIO, @INSS OUTPUT

			-- SETANDO OS PROVENTOS
			EXEC SP_SOMAR_PROVENTOS @MATRICULA_FUNCIONARIO, @PROVENTOS OUTPUT

			-- SETANDOS A DEDUCAO POR DEPENDENTES
			EXEC SP_DEDUCAO_POR_DEPENDENTE @MATRICULA_FUNCIONARIO, @DEPENDENTES OUTPUT

			-- SETANDO A BASE DE CALCULO -> (SALARIO + PROVENTOS – INSS)
			SET @BASE_CALCULO = @SALARIO_BRUTO + @PROVENTOS - @INSS - @DEPENDENTES

			-- SETANDO OS VALORES DA ALIQUOTA E PARC
			SELECT	@ALIQUOTA = ALIQ,
					@PARC = PARC
			FROM IRRF
			WHERE @BASE_CALCULO > VMIN AND @BASE_CALCULO <=VMAX

			-- SETANDO O VALOR DO IMPOSTO DE RENDA
			SET @VALOR_IRRF = (@BASE_CALCULO * (@ALIQUOTA / 100)) - @PARC

			-- SETANDO O VALOR DO IMPOSTO DE RENDA EM ZERO, CASO POR ALGUM MOTIVO FIQUE NEGATIVO
			IF @VALOR_IRRF < 0
				SET @VALOR_IRRF = 0
		END
	ELSE
		BEGIN
			SET @VALOR_IRRF = -1
			PRINT 'SP_CALCULAR_IRRF: MATRÍCULA INVÁLIDA!'
		END
END

-- TESTE
DECLARE @ROUBADO MONEY
EXEC SP_CALCULAR_IRRF 1002, @ROUBADO OUTPUT
SELECT @ROUBADO AS ROUBADO