CREATE PROCEDURE SP_FOLHA_DE_PAGAMENTO_DE_TODOS
AS
BEGIN
	DECLARE @FUNC VARCHAR(4),
			@PRIMEIRO VARCHAR(4),
			@ULTIMO VARCHAR(4)

	SELECT	@PRIMEIRO = MIN(MATRICULA),
			@ULTIMO = MAX(MATRICULA)
	FROM FUNCIONARIOS

	SET @FUNC = @PRIMEIRO
	WHILE @FUNC BETWEEN @PRIMEIRO AND @ULTIMO
		BEGIN
			IF @FUNC IN (SELECT MATRICULA FROM FUNCIONARIOS)
				BEGIN
					PRINT ''
					EXEC SP_FOLHA_DE_PAGAMENTO @FUNC
					PRINT ''
				END
			SET @FUNC = @FUNC + 1
		END
END

-- CHAMADA DA PROCEDURE
EXEC SP_FOLHA_DE_PAGAMENTO_DE_TODOS