-- PROCEDURE PARA CALCULAR O BONUS POR ESCOLARIDADE (GPE)
ALTER PROCEDURE SP_GRATIFICAO_POR_ESCOLARIDADE
(@SALARIO_BRUTO MONEY, @GRAU_ESCOL VARCHAR(1), @BONUS_GPE MONEY OUTPUT)
AS
BEGIN
	DECLARE @PORC DECIMAL(5,2)
	SET @PORC = (SELECT BONUS_PORC FROM GRATIFICACAO_POR_ESCOLARIDADE WHERE ID LIKE @GRAU_ESCOL) / 100

	SET @BONUS_GPE = @SALARIO_BRUTO * @PORC
END

--TESTE
DECLARE @GPE MONEY
EXEC SP_GRATIFICAO_POR_ESCOLARIDADE 6000, 'G', @GPE OUTPUT
SELECT @GPE AS GPE