-- PROCEDURE DE CALCULO DO SALARIO FAMILIA
ALTER PROCEDURE SP_SALARIO_FAMILIA
(@MATRICULA_FUNCIONARIO VARCHAR(4), @SALARIO_FAMILIA MONEY OUTPUT)
AS
BEGIN
	IF @MATRICULA_FUNCIONARIO IN (SELECT MATRICULA FROM FUNCIONARIOS)
		BEGIN
			-- VARIAVEL DA PROCEDURE
			DECLARE @SALARIO_BRUTO MONEY

			-- DEFININDO O SALARIO BRUTO 
			EXEC SP_SALARIO_BRUTO @MATRICULA_FUNCIONARIO, @SALARIO_BRUTO
	
			SET @SALARIO_FAMILIA = (SELECT S_FAMILIA FROM SALARIO_FAMILIA WHERE @SALARIO_BRUTO BETWEEN SMIN AND SMAX)
			IF @SALARIO_FAMILIA IS NULL
				SET @SALARIO_FAMILIA = 0
		END
	ELSE
		BEGIN
			SET @SALARIO_FAMILIA = -1
			PRINT 'SP_SALARIO_FAMILIA: MATRICULA INVALIDO!'
		END
END

-- TESTE
DECLARE @SAL_FAM MONEY
EXEC SP_SALARIO_FAMILIA 1060, @SAL_FAM OUTPUT
SELECT @SAL_FAM AS SALARIO_FAMILY