-- PROCEDURE DE CALCULO DO SALARIO FAMILIA
CREATE PROCEDURE SP_SALARIO_FAMILIA
(@SALARIO_BRUTO MONEY, @SALARIO_FAMILIA MONEY OUTPUT)
AS
BEGIN
	SET @SALARIO_FAMILIA = (SELECT S_FAMILIA FROM SALARIO_FAMILIA WHERE @SALARIO_BRUTO BETWEEN SMIN AND SMAX)
	IF @SALARIO_FAMILIA IS NULL
		SET @SALARIO_FAMILIA = 0
END

-- TESTE
DECLARE @SAL_FAM MONEY
EXEC SP_SALARIO_FAMILIA 150, @SAL_FAM OUTPUT
SELECT @SAL_FAM AS SALARIO_FAMILY