--
CREATE PROCEDURE SP_ANUENIO
(@MATRICULA VARCHAR(4), @BONUS_ANUENIO MONEY OUTPUT)
AS
BEGIN
	DECLARE @DATA_ATUAL DATE,
			@DATA_ADMISSAO DATE,
			@BONUS_PAT DECIMAL(5,2), 
			@ANOS_TRAB INT

	SET @DATA_ATUAL = CONVERT(DATE,GETDATE())

	SET @DATA_ADMISSAO = (SELECT ADMISSAO FROM FUNCIONARIOS WHERE MATRICULA = @MATRICULA)
	
	SET @BONUS_PAT = (SELECT * FROM BONUS_POR_ANO_TRABALHADO)
	
	SET @ANOS_TRAB = CONVERT(INT, DATEDIFF(DAY, @DATA_ADMISSAO, @DATA_ATUAL) / 365.25)
	
	SET @BONUS_ANUENIO =  @ANOS_TRAB * @BONUS_PAT

END

-- TESTE
DECLARE @BONUSITO MONEY
EXEC SP_ANUENIO '1060', @BONUSITO OUTPUT
SELECT @BONUSITO