--
CREATE PROCEDURE SP_ANUENIO
(@MATRICULA VARCHAR(4), @BONUS_ANUENIO MONEY OUTPUT)
AS
BEGIN
	--VARIVEIS DA PROCEDURE
	DECLARE @DATA_ATUAL DATE,
			@DATA_ADMISSAO DATE,
			@BONUS_PAT DECIMAL(5,2), 
			@ANOS_TRAB INT

	-- PEGANDO A DATA DO SISTEMA E CONVERTENDO PARA O TIPO DATE
	SET @DATA_ATUAL = CONVERT(DATE,GETDATE())

	-- PEGANDO A DATA QUE O FUNCIONARIO FOI CONTRATADO
	SET @DATA_ADMISSAO = (SELECT ADMISSAO FROM FUNCIONARIOS WHERE MATRICULA = @MATRICULA)
	
	-- PEGANDO O VALOR DO BONUS POR ANO TRABALHADO
	SET @BONUS_PAT = (SELECT * FROM BONUS_POR_ANO_TRABALHADO)
	
	-- OBTENDO A DIFERENÇA ENTRE A DATA ATUAL E A DATA EM QUE O FUNCIONARIO FOI CONTRATADO
	SET @ANOS_TRAB = CONVERT(INT, DATEDIFF(DAY, @DATA_ADMISSAO, @DATA_ATUAL) / 365.25)
	
	-- DEFININDO O BONUS POR ANO(S) DE TRABALHO(S)
	SET @BONUS_ANUENIO =  @ANOS_TRAB * @BONUS_PAT

END

-- TESTE
DECLARE @BONUSITO MONEY
EXEC SP_ANUENIO 1060, @BONUSITO OUTPUT
SELECT @BONUSITO