USE DB_INSTITUTO
ALTER PROCEDURE SP_CALCULAR_INSS
(@SALARIO_CONTRIBUICAO MONEY, @DESCONTO_INSS MONEY OUTPUT)
AS
BEGIN
	DECLARE	@ALIQUOTA DECIMAL(5,3),
			@DIFERENCA MONEY,
			@AGREGADO MONEY,
			@FAIXA INT

	-- VERIFICANDO SE O SALARIO É MAIOR QUE O TETO DO INSS, SE FOR RETORNAR O DESCONTO_INSS E ENCERRA A PROCEDURE
	IF @SALARIO_CONTRIBUICAO > (SELECT VMAX FROM CONTRIBUICAO_PREVIDENCIARIA_INSS WHERE FAIXA = 4)
		BEGIN
			SET @DESCONTO_INSS = (SELECT SUM((VMAX-VMIN) * (ALIQUOTA/100)) FROM CONTRIBUICAO_PREVIDENCIARIA_INSS)
		END
	-- SE NÃO FOR MAIOR, EXECUTA ISSO
	ELSE 
		BEGIN
			SELECT	@FAIXA = FAIXA,				-- DEFININDO A FAIXA
					@ALIQUOTA = ALIQUOTA / 100,	-- DEFININDO A ALIQUOTA
					@DIFERENCA = VMIN			-- DEFININDO A DIFERENÇA
			FROM CONTRIBUICAO_PREVIDENCIARIA_INSS
			WHERE @SALARIO_CONTRIBUICAO BETWEEN VMIN AND VMAX

			-- ADICIONANDO VALOR A AGREGAR
			SET @AGREGADO = 0
			IF @FAIXA > 1 -- SE FOR DA FAIXA 1 NÃO PRECISA AGREGAR NADA
				BEGIN
					SET @AGREGADO = ((SELECT SUM((VMAX-VMIN) * (ALIQUOTA/100))
									 FROM CONTRIBUICAO_PREVIDENCIARIA_INSS
									 WHERE FAIXA < @FAIXA))
				END

			--DEFININDO A DIFERENÇA A SER TIRADA
			SET @DESCONTO_INSS = ((@SALARIO_CONTRIBUICAO - @DIFERENCA) * (@ALIQUOTA)) + @AGREGADO
		END
END


--CHAMADA DA PROCEDURE
DECLARE	@SALARIO MONEY,
		@INSS MONEY
SET @SALARIO = 7000
EXEC SP_CALCULAR_INSS @SALARIO, @INSS OUTPUT 
SELECT CONVERT(DECIMAL(5,2), @INSS) AS DESCONTO_DO_INSS