ALTER PROCEDURE SP_VALE_TRANSPORTE
(@MATRICULA_FUNCIONARIO VARCHAR(4), @VALE_TRANSPORTE MONEY OUTPUT)
AS
BEGIN
	IF @MATRICULA_FUNCIONARIO IN (SELECT MATRICULA FROM FUNCIONARIOS)
		BEGIN
			-- SE TIVER DESCONTO E DIREITO, SERÁ CALCULADO
			IF @MATRICULA_FUNCIONARIO IN (SELECT MATRICULA FROM FUNCIONARIOS WHERE VALE_TRANSP = 'S')
				BEGIN
					-- VARIAVEL LOCAL
					DECLARE @SALARIO_BRUTO MONEY

					-- SETANDO VALOR DO SALARIO BRUTO
					EXEC SP_SALARIO_BRUTO @MATRICULA_FUNCIONARIO, @SALARIO_BRUTO OUTPUT

					SELECT @VALE_TRANSPORTE = @SALARIO_BRUTO * PORC / 100 FROM VALE_TRANSPORTE
				END
			ELSE -- SE NÃO TIVER O DESCONTO
				BEGIN
					SET @VALE_TRANSPORTE = 0
				END
		END
	ELSE
		BEGIN
			SET @VALE_TRANSPORTE = -1
			PRINT 'SP_VALE_TRANSPORTE: MATRÍCULA INVÁLIDA'
		END
END

-- TESTE
/* MATRICULAS COM 'S' NO VALE_TRANSP
1002
1010
1045
1054
1065
1067

IMMPRESSÃO DESSAS PESSOAS

SELECT F.MATRICULA, F.NOME, C.SALARIO, CONVERT(MONEY, (C.SALARIO*6/100)) AS VALE_TRANSPORTE 
FROM FUNCIONARIOS F
INNER JOIN CARGOS C ON C.CARGO = F.CARGO
WHERE VALE_TRANSP = 'S'
*/

DECLARE @VALE MONEY
EXEC SP_VALE_TRANSPORTE 1060, @VALE OUTPUT
SELECT @VALE AS VALE_TRANSPORTE
