-- PROCEDURE PARA CALCULAR O DESCONTO DO PLANO DE SAUDE
ALTER PROCEDURE SP_PLANO_SAUDE
(@MATRICULA_FUNCIONARIO VARCHAR(4), @DESCONTO_PLANO_SAUDE MONEY OUTPUT)
AS
BEGIN
	IF @MATRICULA_FUNCIONARIO IN (SELECT MATRICULA FROM FUNCIONARIOS)
		BEGIN
			-- VARIAVEL DA PROCEDURE
			DECLARE @TAXA_FUNCIONARIO DECIMAL(5,2),
					@TAXA_DEPENDENTE DECIMAL(5,2),
					@DEPENDENTE INT,
					@PLANO_SAUDE CHAR(5),
					@SALARIO_BRUTO MONEY

			-- DEFININDO SALARIO BRUTO
			EXEC SP_SALARIO_BRUTO @MATRICULA_FUNCIONARIO, @SALARIO_BRUTO OUTPUT

			-- DEFININDO AS TAXAS
			SELECT @TAXA_FUNCIONARIO = TAXA_FUNCIONARIO, @TAXA_DEPENDENTE =	TAXA_DEPENDENTE FROM PLANO_SAUDE_EMPRESARIAL

			-- EXTRAINDO INFORMAÇÕES PARA REALIZAR OS CALCULOS
			SELECT @PLANO_SAUDE = PLANO_SAUDE, @DEPENDENTE = DEPENDENTES FROM FUNCIONARIOS WHERE MATRICULA = @MATRICULA_FUNCIONARIO

			IF @PLANO_SAUDE = 'S' 
				IF @DEPENDENTE = 0
				SET @DESCONTO_PLANO_SAUDE = @SALARIO_BRUTO * (@TAXA_FUNCIONARIO/100)
				IF @DEPENDENTE > 0
				SET @DESCONTO_PLANO_SAUDE = @SALARIO_BRUTO * ((@TAXA_FUNCIONARIO + (@TAXA_DEPENDENTE*@DEPENDENTE))/100)

			IF @PLANO_SAUDE = 'N'
				SET @DESCONTO_PLANO_SAUDE = 0
		END
	ELSE 
		BEGIN
			SET @DESCONTO_PLANO_SAUDE = -1
			PRINT 'SP_PLANO_SAUDE: MATRÍCULA INVÁLIDA!'
		END
END

-- TESTE
DECLARE @DESCO_SAUDE MONEY 
EXEC SP_PLANO_SAUDE  1002,@DESCO_SAUDE OUTPUT
SELECT @DESCO_SAUDE AS DESCONTO_PLANO_SAUDE