USE DB_INSTITUTO

-- CRIAÇÃO DA TABELA DE GRATIFICAÇÃO POR ESCOLARIDADE
CREATE TABLE GRATIFICACAO_POR_ESCOLARIDADE(
	ID CHAR(1),
	ESCOLARIDADE VARCHAR(20) NOT NULL,
	BONUS_PORC DECIMAL(5,2) NOT NULL,
	PRIMARY KEY(ID)
)

-- INSERINDO VALORES
INSERT INTO GRATIFICACAO_POR_ESCOLARIDADE
VALUES
('S', 'MEDIO', 0),
('G', 'GRADUADO', 18),
('E', 'ESPECIALIZACAO', 25),
('M', 'MESTRADO', 54),
('D', 'DOUTORADO', 104)

-- SELECT
SELECT * FROM GRATIFICACAO_POR_ESCOLARIDADE ORDER BY BONUS_PORC