-- 
USE DB_INSTITUTO

--
CREATE TABLE PLANO_SAUDE_EMPRESARIAL
(
	TAXA_FUNCIONARIO NUMERIC(5,2) NOT NULL,
	TAXA_DEPENDENTE NUMERIC(5,2) NOT NULL
)

--

INSERT INTO PLANO_SAUDE_EMPRESARIAL (TAXA_FUNCIONARIO, TAXA_DEPENDENTE) VALUES (3.75, 1.15)

--
SELECT * FROM PLANO_SAUDE_EMPRESARIAL