-- CRIANDO A TABELA CONTENDO O VALOR A DEDUZIR DO DEPENDENTE
CREATE TABLE DEPENDENTE (
	DEDUCAO MONEY NOT NULL
)

-- INSERINDO O VALOR
INSERT INTO DEPENDENTE VALUES (189.59)

-- TESTE
SELECT * FROM DEPENDENTE