-- 
USE DB_INSTITUTO

--
CREATE TABLE SALARIO_FAMILIA(
	FAIXA INT,
	SMIN MONEY NOT NULL,
	SMAX MONEY NOT NULL,
	S_FAMILIA MONEY NOT NULL,
	PRIMARY KEY(FAIXA)
)

--
INSERT INTO SALARIO_FAMILIA VALUES
(1, 0, 859.88, 44.09),
(2, 869.89, 1292.43, 31.07)

--
SELECT * FROM SALARIO_FAMILIA